sudo: required
services:
  - docker

before_install:
  - docker build -t ryantwms/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ryantwms/react-test npm test -- --coverage

after_success:
  - docker build -t ryantwms/multi-client -f ./client
  - docker build -t ryantwms/multi-nginz -f ./nginx
  - docker build -t ryantwms/multi-server -f ./server
  - docker build -t ryantwms/multi-worker -f ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push tem to docker hub
  - docker push ryantwms/multi-client
  - docker push ryantwms/multi-nginx
  - docker push ryantwms/multi-server
  - docker push ryantwms/multi-worker
